es:
  errors:
    messages:
      not_found: 'Recurso con id %{id} no encontrado'
